### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by jsdhasfedssad** [ZeroMemoryEx/Amsi-Killer#4]
This does not seem to work for me. Alternatively, I am doing something wrong.

![amsi1](https://user-images.githubusercontent.com/97032878/222170723-8992c82b-4720-41bb-8770-d680bc184195.png)

**Comment by xenoantic** [comment]
My pattern is different then what was coded so it is not working for me: 
```
amsi!AmsiOpenSession:
00007ffd`a7df37e0 4885d2          test    rdx,rdx
00007ffd`a7df37e3 7447            je      amsi!AmsiOpenSession+0x4c (00007ffd`a7df382c)
00007ffd`a7df37e5 4885c9          test    rcx,rcx
00007ffd`a7df37e8 7442            je      amsi!AmsiOpenSession+0x4c (00007ffd`a7df382c)
00007ffd`a7df37ea 8139414d5349    cmp     dword ptr [rcx],49534D41h
00007ffd`a7df37f0 753a            jne     amsi!AmsiOpenSession+0x4c (00007ffd`a7df382c)
00007ffd`a7df37f2 4883790800      cmp     qword ptr [rcx+8],0
00007ffd`a7df37f7 7433            je      amsi!AmsiOpenSession+0x4c (00007ffd`a7df382c)
```

Updating the BYTE pattern[] to the following fixed the issue for me: 

`BYTE pattern[] = { 0x48,'?','?', 0x74,'?',0x48,'?' ,'?' ,0x74,'?' };`

**Comment by ZeroMemoryEx** [comment]
hello @jsdhasfedssad  yes its working perfectly , can you please screenshot the 'amsi-killer' console output

**Comment by ZeroMemoryEx** [comment]
Hello @jsdhasfedssad , yes, it's working perfectly. The problem in your case is that there is another PowerShell program running in the background. Please go to the task manager, terminate any open PowerShell programs, and then try again. This will solve your issue.

**Comment by ZeroMemoryEx** [comment]
if the problem solved lemme know to close the issue ticket @jsdhasfedssad .

**Comment by xenoantic** [comment]
I've run this on 2 separate Windows machines and have the same issue. Your search pattern does not match the memory location in my amsi!AmsiOpenSession.

**Comment by ZeroMemoryEx** [comment]
hello @xenoantic  Please go the task manager and terminate any open PowerShell programs, and then try again

**Comment by ZeroMemoryEx** [comment]
it seems that i should add a functionality to close any open powershell in the background or spawn a patched one !!

**Comment by xenoantic** [comment]
I do not have any other PowerShell sessions open except the one I'm attached to in WinDBG which needs to be open in order to access the AmsiOpenSession.  It seems your code does not account for all versions my 8139414d5349 cmp instruction is different then the one in your screenshots and thus your pattern does not match mine. I've given you a solution above and implemented it and have a working program: 

![image](https://user-images.githubusercontent.com/25680228/222237704-dbc710e7-ca27-4869-a2bc-fc8d42a17cba.png)

**Comment by ZeroMemoryEx** [comment]
@xenoantic thank you for mentioning it ,can you tell me what windows version you have ?

**Comment by ZeroMemoryEx** [comment]
problem solved

**Comment by jsdhasfedssad** [comment]
Closing other Powershell sessions does not help. This is executed on Server 2019.

**Comment by ZeroMemoryEx** [comment]
hello @jsdhasfedssad  the search pattern has been updated to work in all windows versions , please try again wth the updated version of the program .

**Comment by ZeroMemoryEx** [comment]
![image](https://user-images.githubusercontent.com/60795188/222785542-2e01b918-87eb-4def-a341-ae6b3c48bc71.png)

**Comment by ZeroMemoryEx** [comment]
tested on windows server 2022
