### ISSUE TITLE
Can you please tell, how to run the exe.

### ISSUE THREAD

**Issue by black-arch7** [ZeroMemoryEx/Amsi-Killer#5]
When i try to run amsi-killer, no outpt nor any help menu and when i passed exe as argument still no output and no changes in passed exe.

Really helpful if you tell how to use

**Comment by ZeroMemoryEx** [comment]
Hello @black-arch7 , could you please provide a screenshot of the problem? Alternatively, you can watch this video that covers how to use it 
https://www.youtube.com/watch?v=QFp3ybRKr7Q

**Comment by ZeroMemoryEx** [comment]
if the problem solved lemme know to close the issue !

**Comment by black-arch7** [comment]
Yes, problem solved..Thanks alot for quick response and sorry bothered you with silly question.

**Comment by ZeroMemoryEx** [comment]
Happy to hear that. You're welcome !!
